package io.uvera.helmetreactivespringbootstarter.configuration

import io.uvera.helmetreactivespringbootstarter.properties.HelmetReactiveProperties
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(HelmetReactiveProperties::class)
class HelmetReactiveConfiguration
